### ISSUE TITLE
See an org's impact area on card

### ISSUE THREAD

**Issue by frhino** [oviohub/ovio-ideabox#1]
As someone who is interested in finding orgs who work on a specific impact area (falling under a larger umbrella impact area), I need a way to find the impact area of an org that I know is working on that issue, so that I can know how Ovio has categorized orgs working on that issue.

My first instinct was to look for text tags.

**Comment by ericboucher** [comment]
This is now live on https://explore.ovio.org 
And you can click on a logo to filter by the impact area!
