### ISSUE TITLE
no link to repo selection

### ISSUE THREAD

**Issue by Catalinex** [oviohub/ovio-ideabox#4]
if i make a selection i would like to be able to share the link

**Comment by ericboucher** [comment]
Neat idea @Catalinex! To clarify, do you mean that you would like to share your filters and the projects that go with it, or share one particular project easily? This last feature is coming soon!

**Comment by ericboucher** [comment]
Hi @Catalinex, the Ovio URL now updates with your search parameters, making it easy for you to share the link with your friends!

Let us know if that fits your need and don't hesitate to share other ideas!!
