### ISSUE TITLE
Closed issues in Tasks & Issues

### ISSUE THREAD

**Issue by KonradLinkowski** [oviohub/ovio-ideabox#6]
I don't understand what's the point of closed issues in Tasks & Issues.
Shouldn't those issues be marked as closed somehow?
Example project: https://ovio.org/project/Vizzuality/gfw

**Comment by ericboucher** [comment]
@KonradLinkowski thanks for your feedback! We've made quite a few updates on the issue column for projects and closed and assigned issues are not showing anymore.

Have a look at our brand new expanded issue search on https://ovio.org/project/Vizzuality/gfw :)

**Comment by KonradLinkowski** [comment]
Cool, thanks :)
